name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_humble:
    name: build humble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ros2-humble/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:humble
          cache-from: type=gha
          cache-to: type=gha,mode=max